import type { Locality } from "./types";

/**
 * Localities — the facet the incumbent does not have.
 *
 * The incumbent's region map contains six regions and roughly thirty
 * sub-areas, and not one Arab-majority town appears in any of them. No facet
 * means no landing page, no organic traffic, no supply. This file is the fix.
 *
 * Coverage: the Arab localities of Israel by population, the mixed cities, and
 * the Jewish-majority university cities (Arab students both study and tutor
 * there, and online lessons are location-agnostic anyway).
 *
 * Population figures are approximate and rounded — refresh against Central
 * Bureau of Statistics data before showing them to users.
 */
export const localities: Locality[] = [
  // ── Galilee ────────────────────────────────────────────────────────────────
  {
    slug: "nazareth",
    ar: "الناصرة",
    he: "נצרת",
    en: "Nazareth",
    aliases: ["nasra", "nazareth", "الناصره"],
    district: "galilee",
    population: 75700,
    arabMajority: true,
    featured: true,
  },
  {
    slug: "shefa-amr",
    ar: "شفاعمرو",
    he: "שפרעם",
    en: "Shefa-Amr",
    aliases: ["shfaram", "shefaram"],
    district: "galilee",
    population: 42000,
    arabMajority: true,
    featured: true,
  },
  {
    slug: "tamra",
    ar: "طمرة",
    he: "טמרה",
    en: "Tamra",
    district: "galilee",
    population: 35000,
    arabMajority: true,
    featured: true,
  },
  {
    slug: "sakhnin",
    ar: "سخنين",
    he: "סח'נין",
    en: "Sakhnin",
    aliases: ["sachnin"],
    district: "galilee",
    population: 32000,
    arabMajority: true,
    featured: true,
  },
  {
    slug: "arraba",
    ar: "عرابة",
    he: "עראבה",
    en: "Arraba",
    district: "galilee",
    population: 26000,
    arabMajority: true,
  },
  {
    slug: "kafr-kanna",
    ar: "كفر كنا",
    he: "כפר כנא",
    en: "Kafr Kanna",
    district: "galilee",
    population: 23000,
    arabMajority: true,
  },
  {
    slug: "maghar",
    ar: "المغار",
    he: "מגאר",
    en: "Maghar",
    district: "galilee",
    population: 22000,
    arabMajority: true,
  },
  {
    slug: "jadeidi-makr",
    ar: "الجديدة-المكر",
    he: "ג'דיידה-מכר",
    en: "Jadeidi-Makr",
    district: "galilee",
    population: 22000,
    arabMajority: true,
  },
  {
    slug: "kafr-manda",
    ar: "كفر مندا",
    he: "כפר מנדא",
    en: "Kafr Manda",
    district: "galilee",
    population: 20000,
    arabMajority: true,
  },
  {
    slug: "yafa-an-naseriyye",
    ar: "يافة الناصرة",
    he: "יפיע",
    en: "Yafa an-Naseriyye",
    district: "galilee",
    population: 19000,
    arabMajority: true,
  },
  {
    slug: "reineh",
    ar: "الرينة",
    he: "ריינה",
    en: "Reineh",
    district: "galilee",
    population: 19000,
    arabMajority: true,
  },
  {
    slug: "yarka",
    ar: "يركا",
    he: "ירכא",
    en: "Yarka",
    district: "galilee",
    population: 17000,
    arabMajority: true,
  },
  {
    slug: "majd-al-krum",
    ar: "مجد الكروم",
    he: "מג'ד אל-כרום",
    en: "Majd al-Krum",
    district: "galilee",
    population: 15000,
    arabMajority: true,
  },
  {
    slug: "abu-snan",
    ar: "أبو سنان",
    he: "אבו סנאן",
    en: "Abu Snan",
    district: "galilee",
    population: 14000,
    arabMajority: true,
  },
  {
    slug: "ibillin",
    ar: "عبلين",
    he: "אעבלין",
    en: "I'billin",
    district: "galilee",
    population: 14000,
    arabMajority: true,
  },
  {
    slug: "kabul",
    ar: "كابول",
    he: "כאבול",
    en: "Kabul",
    district: "galilee",
    population: 14000,
    arabMajority: true,
  },
  {
    slug: "iksal",
    ar: "إكسال",
    he: "אכסאל",
    en: "Iksal",
    district: "galilee",
    population: 14000,
    arabMajority: true,
  },
  {
    slug: "turan",
    ar: "طرعان",
    he: "טורעאן",
    en: "Turan",
    district: "galilee",
    population: 14000,
    arabMajority: true,
  },
  {
    slug: "nahf",
    ar: "نحف",
    he: "נחף",
    en: "Nahf",
    district: "galilee",
    population: 13000,
    arabMajority: true,
  },
  {
    slug: "beit-jann",
    ar: "بيت جن",
    he: "בית ג'ן",
    en: "Beit Jann",
    district: "galilee",
    population: 12000,
    arabMajority: true,
  },
  {
    slug: "daburiyya",
    ar: "دبورية",
    he: "דבוריה",
    en: "Daburiyya",
    district: "galilee",
    population: 11000,
    arabMajority: true,
  },
  {
    slug: "deir-hanna",
    ar: "دير حنا",
    he: "דיר חנא",
    en: "Deir Hanna",
    district: "galilee",
    population: 10000,
    arabMajority: true,
  },
  {
    slug: "kafr-yasif",
    ar: "كفر ياسيف",
    he: "כפר יאסיף",
    en: "Kafr Yasif",
    district: "galilee",
    population: 10000,
    arabMajority: true,
  },
  {
    slug: "mashhad",
    ar: "مشهد",
    he: "משהד",
    en: "Mashhad",
    district: "galilee",
    population: 9000,
    arabMajority: true,
  },
  {
    slug: "ilut",
    ar: "عيلوط",
    he: "עילוט",
    en: "Ilut",
    district: "galilee",
    population: 9000,
    arabMajority: true,
  },
  {
    slug: "bina",
    ar: "البعنة",
    he: "בענה",
    en: "Bi'na",
    district: "galilee",
    population: 9000,
    arabMajority: true,
  },
  {
    slug: "rameh",
    ar: "الرامة",
    he: "ראמה",
    en: "Rameh",
    district: "galilee",
    population: 8000,
    arabMajority: true,
  },
  {
    slug: "eilabun",
    ar: "عيلبون",
    he: "עילבון",
    en: "Eilabun",
    district: "galilee",
    population: 6000,
    arabMajority: true,
  },
  {
    slug: "shaab",
    ar: "شعب",
    he: "שעב",
    en: "Sha'ab",
    district: "galilee",
    population: 7000,
    arabMajority: true,
  },
  {
    slug: "peki-in",
    ar: "البقيعة",
    he: "פקיעין",
    en: "Peki'in",
    district: "galilee",
    population: 6000,
    arabMajority: true,
  },
  {
    slug: "julis",
    ar: "جولس",
    he: "ג'וליס",
    en: "Julis",
    district: "galilee",
    population: 7000,
    arabMajority: true,
  },
  {
    slug: "kisra-sumei",
    ar: "كسرى-سميع",
    he: "כסרא-סמיע",
    en: "Kisra-Sumei",
    district: "galilee",
    population: 8000,
    arabMajority: true,
  },
  {
    slug: "zarzir",
    ar: "الزرازير",
    he: "זרזיר",
    en: "Zarzir",
    district: "galilee",
    population: 8000,
    arabMajority: true,
  },
  {
    slug: "tuba-zangariyye",
    ar: "طوبا الزنغرية",
    he: "טובא-זנגריה",
    en: "Tuba-Zangariyye",
    district: "galilee",
    population: 7000,
    arabMajority: true,
  },
  {
    slug: "basmat-tabun",
    ar: "بسمة طبعون",
    he: "בסמת טבעון",
    en: "Basmat Tab'un",
    district: "galilee",
    population: 6000,
    arabMajority: true,
  },
  {
    slug: "kawkab-abu-al-hija",
    ar: "كوكب أبو الهيجاء",
    he: "כאוכב אבו אל-היג'א",
    en: "Kawkab Abu al-Hija",
    district: "galilee",
    population: 4000,
    arabMajority: true,
  },
  {
    slug: "sajur",
    ar: "ساجور",
    he: "סאג'ור",
    en: "Sajur",
    district: "galilee",
    population: 4000,
    arabMajority: true,
  },

  // ── Triangle ───────────────────────────────────────────────────────────────
  {
    slug: "umm-al-fahm",
    ar: "أم الفحم",
    he: "אום אל-פחם",
    en: "Umm al-Fahm",
    aliases: ["umm el fahem", "أم الفحم"],
    district: "triangle",
    population: 60200,
    arabMajority: true,
    featured: true,
  },
  {
    slug: "tayibe",
    ar: "الطيبة",
    he: "טייבה",
    en: "Tayibe",
    aliases: ["taibe", "taybeh"],
    district: "triangle",
    population: 45400,
    arabMajority: true,
    featured: true,
  },
  {
    slug: "baqa-al-gharbiyye",
    ar: "باقة الغربية",
    he: "באקה אל-גרביה",
    en: "Baqa al-Gharbiyye",
    aliases: ["baka", "baqa"],
    district: "triangle",
    population: 30000,
    arabMajority: true,
    featured: true,
  },
  {
    slug: "tira",
    ar: "الطيرة",
    he: "טירה",
    en: "Tira",
    district: "triangle",
    population: 27000,
    arabMajority: true,
    featured: true,
  },
  {
    slug: "arara",
    ar: "عرعرة",
    he: "ערערה",
    en: "Ar'ara",
    aliases: ["ara", "عارة"],
    district: "triangle",
    population: 26000,
    arabMajority: true,
  },
  {
    slug: "kafr-qasim",
    ar: "كفر قاسم",
    he: "כפר קאסם",
    en: "Kafr Qasim",
    district: "triangle",
    population: 24000,
    arabMajority: true,
    featured: true,
  },
  {
    slug: "qalansawe",
    ar: "قلنسوة",
    he: "קלנסווה",
    en: "Qalansawe",
    district: "triangle",
    population: 24000,
    arabMajority: true,
  },
  {
    slug: "kafr-qara",
    ar: "كفر قرع",
    he: "כפר קרע",
    en: "Kafr Qara",
    district: "triangle",
    population: 19000,
    arabMajority: true,
  },
  {
    slug: "jatt",
    ar: "جت",
    he: "ג'ת",
    en: "Jatt",
    district: "triangle",
    population: 12000,
    arabMajority: true,
  },
  {
    slug: "jaljulia",
    ar: "جلجولية",
    he: "ג'לג'וליה",
    en: "Jaljulia",
    district: "triangle",
    population: 10000,
    arabMajority: true,
  },
  {
    slug: "zemer",
    ar: "زيمر",
    he: "זמר",
    en: "Zemer",
    district: "triangle",
    population: 8000,
    arabMajority: true,
  },
  {
    slug: "basma",
    ar: "بسمة",
    he: 'בסמ"ה',
    en: "Basma",
    district: "triangle",
    population: 9000,
    arabMajority: true,
  },
  {
    slug: "kafr-bara",
    ar: "كفر برا",
    he: "כפר ברא",
    en: "Kafr Bara",
    district: "triangle",
    population: 4000,
    arabMajority: true,
  },

  // ── Negev ──────────────────────────────────────────────────────────────────
  {
    slug: "rahat",
    ar: "رهط",
    he: "רהט",
    en: "Rahat",
    district: "negev",
    population: 78000,
    arabMajority: true,
    featured: true,
  },
  {
    slug: "hura",
    ar: "حورة",
    he: "חורה",
    en: "Hura",
    district: "negev",
    population: 23000,
    arabMajority: true,
  },
  {
    slug: "tel-as-sabi",
    ar: "تل السبع",
    he: "תל שבע",
    en: "Tel as-Sabi",
    district: "negev",
    population: 22000,
    arabMajority: true,
  },
  {
    slug: "kuseife",
    ar: "كسيفة",
    he: "כסייפה",
    en: "Kuseife",
    district: "negev",
    population: 21000,
    arabMajority: true,
  },
  {
    slug: "ararat-an-naqab",
    ar: "عرعرة النقب",
    he: "ערערה בנגב",
    en: "Ar'arat an-Naqab",
    district: "negev",
    population: 17000,
    arabMajority: true,
  },
  {
    slug: "lakiya",
    ar: "اللقية",
    he: "לקיה",
    en: "Lakiya",
    district: "negev",
    population: 13000,
    arabMajority: true,
  },
  {
    slug: "segev-shalom",
    ar: "شقيب السلام",
    he: "שגב שלום",
    en: "Segev Shalom",
    district: "negev",
    population: 12000,
    arabMajority: true,
  },

  // ── Carmel & Golan (Druze) ─────────────────────────────────────────────────
  {
    slug: "daliyat-al-karmel",
    ar: "دالية الكرمل",
    he: "דלית אל-כרמל",
    en: "Daliyat al-Karmel",
    district: "carmel-golan",
    population: 17000,
    arabMajority: true,
  },
  {
    slug: "isfiya",
    ar: "عسفيا",
    he: "עוספיא",
    en: "Isfiya",
    district: "carmel-golan",
    population: 12000,
    arabMajority: true,
  },
  {
    slug: "majdal-shams",
    ar: "مجدل شمس",
    he: "מג'דל שמס",
    en: "Majdal Shams",
    district: "carmel-golan",
    population: 11000,
    arabMajority: true,
  },
  {
    slug: "buqata",
    ar: "بقعاثا",
    he: "בוקעאתא",
    en: "Buq'ata",
    district: "carmel-golan",
    population: 7000,
    arabMajority: true,
  },
  {
    slug: "masade",
    ar: "مسعدة",
    he: "מסעדה",
    en: "Mas'ade",
    district: "carmel-golan",
    population: 4000,
    arabMajority: true,
  },
  {
    slug: "ein-qiniyye",
    ar: "عين قنية",
    he: "עין קנייא",
    en: "Ein Qiniyye",
    district: "carmel-golan",
    population: 2500,
    arabMajority: true,
  },

  // ── Mixed cities ───────────────────────────────────────────────────────────
  {
    slug: "haifa",
    ar: "حيفا",
    he: "חיפה",
    en: "Haifa",
    aliases: ["haifa", "خيفا"],
    district: "mixed",
    population: 290000,
    arabMajority: false,
    featured: true,
  },
  {
    slug: "acre",
    ar: "عكا",
    he: "עכו",
    en: "Acre",
    aliases: ["akka", "akko"],
    district: "mixed",
    population: 50000,
    arabMajority: false,
    featured: true,
  },
  {
    slug: "lod",
    ar: "اللد",
    he: "לוד",
    en: "Lod",
    aliases: ["lydda", "lud"],
    district: "mixed",
    population: 82000,
    arabMajority: false,
  },
  {
    slug: "ramla",
    ar: "الرملة",
    he: "רמלה",
    en: "Ramla",
    district: "mixed",
    population: 78000,
    arabMajority: false,
  },
  {
    slug: "jaffa",
    ar: "يافا",
    he: "יפו",
    en: "Jaffa",
    aliases: ["yafa", "yafo"],
    district: "mixed",
    arabMajority: false,
    featured: true,
  },
  {
    slug: "nof-hagalil",
    ar: "نوف هجليل",
    he: "נוף הגליל",
    en: "Nof HaGalil",
    aliases: ["upper nazareth", "الناصرة العليا"],
    district: "mixed",
    population: 42000,
    arabMajority: false,
  },
  {
    slug: "maalot-tarshiha",
    ar: "معالوت ترشيحا",
    he: "מעלות-תרשיחא",
    en: "Ma'alot-Tarshiha",
    district: "mixed",
    population: 22000,
    arabMajority: false,
  },

  // ── University cities (supply and demand both concentrate here) ────────────
  {
    slug: "jerusalem",
    ar: "القدس",
    he: "ירושלים",
    en: "Jerusalem",
    aliases: ["quds", "yerushalayim"],
    district: "jerusalem",
    arabMajority: false,
    featured: true,
  },
  {
    slug: "tel-aviv",
    ar: "تل أبيب",
    he: "תל אביב",
    en: "Tel Aviv",
    district: "other",
    arabMajority: false,
    featured: true,
  },
  {
    slug: "beer-sheva",
    ar: "بئر السبع",
    he: "באר שבע",
    en: "Beer Sheva",
    aliases: ["beersheba"],
    district: "other",
    arabMajority: false,
    featured: true,
  },
  {
    slug: "karmiel",
    ar: "كرميئيل",
    he: "כרמיאל",
    en: "Karmiel",
    district: "other",
    arabMajority: false,
  },
  {
    slug: "afula",
    ar: "العفولة",
    he: "עפולה",
    en: "Afula",
    district: "other",
    arabMajority: false,
  },
  {
    slug: "hadera",
    ar: "الخضيرة",
    he: "חדרה",
    en: "Hadera",
    district: "other",
    arabMajority: false,
  },
  {
    slug: "nahariya",
    ar: "نهاريا",
    he: "נהריה",
    en: "Nahariya",
    district: "other",
    arabMajority: false,
  },
  {
    slug: "tiberias",
    ar: "طبريا",
    he: "טבריה",
    en: "Tiberias",
    district: "other",
    arabMajority: false,
  },
];

export const districts = [
  { slug: "galilee", ar: "الجليل", he: "הגליל", en: "Galilee" },
  { slug: "triangle", ar: "المثلث", he: "המשולש", en: "The Triangle" },
  { slug: "negev", ar: "النقب", he: "הנגב", en: "The Negev" },
  {
    slug: "carmel-golan",
    ar: "الكرمل والجولان",
    he: "הכרמל והגולן",
    en: "Carmel and Golan",
  },
  {
    slug: "mixed",
    ar: "المدن المختلطة",
    he: "ערים מעורבות",
    en: "Mixed cities",
  },
  { slug: "jerusalem", ar: "القدس", he: "ירושלים", en: "Jerusalem" },
  { slug: "other", ar: "مناطق أخرى", he: "אזורים אחרים", en: "Other areas" },
] as const;

export const featuredLocalities = localities.filter(
  (locality) => locality.featured,
);

export function findLocality(slug: string) {
  return localities.find((locality) => locality.slug === slug);
}

export function localitiesByDistrict(district: string) {
  return localities.filter((locality) => locality.district === district);
}
