import type { Category } from "./types";

/**
 * Subject taxonomy — built for the Arab school and university track in Israel,
 * not translated from the Hebrew-sector incumbent.
 *
 * Three things here have no equivalent on the incumbent site and are the reason
 * this product exists:
 *   1. `exams` — YAEL and the Arabic-language psychometric, the two gates every
 *      Arabic-speaking university applicant has to clear.
 *   2. `hebrew` as a *second* language, alongside Arabic as a first one.
 *   3. Islamic studies, Christianity and Druze heritage — all bagrut subjects
 *      in Arab schools.
 *
 * Depth is the SEO ammunition: every leaf becomes a landing page. Expand freely.
 */
export const categories: Category[] = [
  {
    slug: "exams",
    ar: "امتحانات القبول",
    he: "בחינות כניסה",
    en: "Entrance exams",
    isExam: true,
    subjects: [
      {
        slug: "yael",
        ar: "يعيل",
        he: 'יע"ל',
        en: "YAEL (Hebrew proficiency)",
        aliases: ["yael", "yaal", "יעל", "امتحان يعيل", "عبري للجامعة"],
        levels: ["professional"],
        featured: true,
      },
      {
        slug: "yaelnet",
        ar: "يعلنت",
        he: "יעלנט",
        en: "Yaelnet",
        aliases: ["yaelnet", "יעלנט"],
        levels: ["professional"],
      },
      {
        slug: "psychometric",
        ar: "بسيخومتري",
        he: "פסיכומטרי",
        en: "Psychometric exam",
        aliases: ["psychometri", "bsychometri", "بسيكومتري", "פסיכומטרי"],
        levels: ["professional"],
        featured: true,
      },
      {
        slug: "psychometric-quantitative",
        ar: "بسيخومتري - كمي",
        he: "פסיכומטרי - כמותי",
        en: "Psychometric — quantitative",
        levels: ["professional"],
      },
      {
        slug: "psychometric-verbal",
        ar: "بسيخومتري - لفظي",
        he: "פסיכומטרי - מילולי",
        en: "Psychometric — verbal",
        levels: ["professional"],
      },
      {
        slug: "amir",
        ar: "أمير",
        he: 'אמי"ר',
        en: "AMIR (English placement)",
        aliases: ["amir", "אמיר", "امتحان امير"],
        levels: ["professional"],
        featured: true,
      },
      {
        slug: "amiram",
        ar: "أميرام",
        he: 'אמיר"ם',
        en: "AMIRAM",
        aliases: ["amiram", "אמירם"],
        levels: ["professional"],
      },
      {
        slug: "mechina",
        ar: "سنة تحضيرية",
        he: "מכינה",
        en: "Mechina (preparatory year)",
        aliases: ["mechina", "مخينا", "מכינה"],
        levels: ["professional"],
      },
      {
        slug: "jordanian-admission",
        ar: "مقياس القبول الأردني",
        he: "מבחן קבלה לאוניברסיטאות בירדן",
        en: "Jordanian university admission",
        aliases: ["مقياس", "الأردن", "ירדן"],
        levels: ["professional"],
      },
      {
        slug: "medicine-abroad",
        ar: "تحضير للطب في الخارج",
        he: 'הכנה ללימודי רפואה בחו"ל',
        en: "Medicine abroad preparation",
        aliases: ["طب", "רפואה", "medicine"],
        levels: ["professional"],
      },
      {
        slug: "toefl",
        ar: "توفل",
        he: "טופל",
        en: "TOEFL",
        aliases: ["toefl", "טופל"],
        levels: ["professional"],
      },
      {
        slug: "ielts",
        ar: "آيلتس",
        he: "איילטס",
        en: "IELTS",
        aliases: ["ielts"],
        levels: ["professional"],
      },
      {
        slug: "gmat",
        ar: "جي مات",
        he: 'ג\'י מא"ט',
        en: "GMAT",
        aliases: ["gmat"],
        levels: ["professional"],
      },
      {
        slug: "gre",
        ar: "جي آر إي",
        he: 'ג\'י.אר.אי',
        en: "GRE",
        aliases: ["gre"],
        levels: ["professional"],
      },
    ],
  },

  {
    slug: "school-core",
    ar: "المواد الأساسية",
    he: "מקצועות ליבה",
    en: "Core school subjects",
    subjects: [
      {
        slug: "mathematics",
        ar: "رياضيات",
        he: "מתמטיקה",
        en: "Mathematics",
        aliases: ["riyadiyat", "math", "matematika", "מתמטיקה", "حساب"],
        levels: ["elementary", "middle", "high", "academic"],
        units: [3, 4, 5],
        featured: true,
      },
      {
        slug: "arabic",
        ar: "اللغة العربية",
        he: "ערבית",
        en: "Arabic language",
        aliases: ["arabi", "عربي", "ערבית", "lugha arabiya"],
        levels: ["elementary", "middle", "high", "academic"],
        units: [3, 4, 5],
        featured: true,
      },
      {
        slug: "hebrew",
        ar: "اللغة العبرية",
        he: "עברית כשפה שנייה",
        en: "Hebrew as a second language",
        aliases: ["ivrit", "عبري", "עברית", "lugha ibriya"],
        levels: ["elementary", "middle", "high", "academic"],
        units: [3, 4, 5],
        featured: true,
      },
      {
        slug: "english",
        ar: "اللغة الإنجليزية",
        he: "אנגלית",
        en: "English",
        aliases: ["english", "إنجليزي", "انجليزي", "אנגלית", "inglizi"],
        levels: ["elementary", "middle", "high", "academic"],
        units: [3, 4, 5],
        featured: true,
      },
      {
        slug: "physics",
        ar: "فيزياء",
        he: "פיזיקה",
        en: "Physics",
        aliases: ["fizya", "physics", "פיזיקה"],
        levels: ["middle", "high", "academic"],
        units: [5],
        featured: true,
      },
      {
        slug: "chemistry",
        ar: "كيمياء",
        he: "כימיה",
        en: "Chemistry",
        aliases: ["kimya", "chemistry", "כימיה"],
        levels: ["middle", "high", "academic"],
        units: [5],
        featured: true,
      },
      {
        slug: "biology",
        ar: "أحياء",
        he: "ביולוגיה",
        en: "Biology",
        aliases: ["ahya", "biology", "بيولوجيا", "ביולוגיה"],
        levels: ["middle", "high", "academic"],
        units: [5],
      },
      {
        slug: "computer-science",
        ar: "علم الحاسوب",
        he: "מדעי המחשב",
        en: "Computer science",
        aliases: ["hasoub", "computers", "מדעי המחשב", "حاسوب"],
        levels: ["middle", "high", "academic"],
        units: [5],
        featured: true,
      },
      {
        slug: "history",
        ar: "تاريخ",
        he: "היסטוריה",
        en: "History",
        levels: ["elementary", "middle", "high", "academic"],
      },
      {
        slug: "civics",
        ar: "مدنيات",
        he: "אזרחות",
        en: "Civics",
        aliases: ["ezrahut", "אזרחות"],
        levels: ["middle", "high"],
      },
      {
        slug: "geography",
        ar: "جغرافيا",
        he: "גאוגרפיה",
        en: "Geography",
        levels: ["elementary", "middle", "high"],
      },
      {
        slug: "literature",
        ar: "أدب",
        he: "ספרות",
        en: "Literature",
        levels: ["middle", "high", "academic"],
      },
      {
        slug: "expression",
        ar: "تعبير وكتابة",
        he: "הבעה וכתיבה",
        en: "Expression and writing",
        levels: ["elementary", "middle", "high"],
      },
      {
        slug: "islamic-studies",
        ar: "الدين الإسلامي",
        he: "דת האסלאם",
        en: "Islamic studies",
        aliases: ["دين", "اسلامية"],
        levels: ["elementary", "middle", "high"],
      },
      {
        slug: "christianity",
        ar: "المسيحية",
        he: "נצרות",
        en: "Christianity",
        levels: ["elementary", "middle", "high"],
      },
      {
        slug: "druze-heritage",
        ar: "التراث الدرزي",
        he: "מורשת דרוזית",
        en: "Druze heritage",
        levels: ["elementary", "middle", "high"],
      },
      {
        slug: "psychology",
        ar: "علم النفس",
        he: "פסיכולוגיה",
        en: "Psychology",
        levels: ["high", "academic"],
      },
      {
        slug: "sociology",
        ar: "علم الاجتماع",
        he: "סוציולוגיה",
        en: "Sociology",
        levels: ["high", "academic"],
      },
    ],
  },

  {
    slug: "academic-math",
    ar: "رياضيات أكاديمية",
    he: "מתמטיקה אקדמית",
    en: "Academic mathematics",
    subjects: [
      {
        slug: "calculus-1",
        ar: "تفاضل وتكامل ١",
        he: 'חדו"א 1',
        en: "Calculus 1",
        aliases: ["hedva", "infi", "אינפי 1", "calculus"],
        levels: ["academic"],
        featured: true,
      },
      {
        slug: "calculus-2",
        ar: "تفاضل وتكامل ٢",
        he: 'חדו"א 2',
        en: "Calculus 2",
        aliases: ["infi 2", "אינפי 2"],
        levels: ["academic"],
      },
      {
        slug: "linear-algebra",
        ar: "جبر خطي",
        he: "אלגברה לינארית",
        en: "Linear algebra",
        aliases: ["algebra", "אלגברה"],
        levels: ["academic"],
        featured: true,
      },
      {
        slug: "probability",
        ar: "احتمالات",
        he: "הסתברות",
        en: "Probability",
        levels: ["academic"],
      },
      {
        slug: "statistics",
        ar: "إحصاء",
        he: "סטטיסטיקה",
        en: "Statistics",
        aliases: ["ihsa", "סטטיסטיקה", "spss"],
        levels: ["high", "academic"],
        featured: true,
      },
      {
        slug: "discrete-mathematics",
        ar: "رياضيات متقطعة",
        he: "מתמטיקה בדידה",
        en: "Discrete mathematics",
        levels: ["academic"],
      },
      {
        slug: "differential-equations",
        ar: "معادلات تفاضلية",
        he: "משוואות דיפרנציאליות",
        en: "Differential equations",
        levels: ["academic"],
      },
    ],
  },

  {
    slug: "economics-accounting",
    ar: "اقتصاد ومحاسبة",
    he: "כלכלה וחשבונאות",
    en: "Economics and accounting",
    subjects: [
      {
        slug: "microeconomics",
        ar: "اقتصاد جزئي",
        he: "מיקרו כלכלה",
        en: "Microeconomics",
        aliases: ["micro", "מיקרו"],
        levels: ["high", "academic"],
      },
      {
        slug: "macroeconomics",
        ar: "اقتصاد كلي",
        he: "מאקרו כלכלה",
        en: "Macroeconomics",
        aliases: ["macro", "מאקרו"],
        levels: ["high", "academic"],
      },
      {
        slug: "financial-accounting",
        ar: "محاسبة مالية",
        he: "חשבונאות פיננסית",
        en: "Financial accounting",
        aliases: ["mohasabe", "חשבונאות"],
        levels: ["high", "academic"],
        featured: true,
      },
      {
        slug: "managerial-accounting",
        ar: "محاسبة إدارية",
        he: "חשבונאות ניהולית",
        en: "Managerial accounting",
        levels: ["academic"],
      },
      {
        slug: "finance",
        ar: "تمويل",
        he: "מימון",
        en: "Finance",
        levels: ["academic"],
      },
      {
        slug: "econometrics",
        ar: "اقتصاد قياسي",
        he: "אקונומטריקה",
        en: "Econometrics",
        levels: ["academic"],
      },
      {
        slug: "business-administration",
        ar: "إدارة أعمال",
        he: "מנהל עסקים",
        en: "Business administration",
        levels: ["academic"],
      },
    ],
  },

  {
    slug: "engineering",
    ar: "هندسة",
    he: "הנדסה",
    en: "Engineering",
    subjects: [
      {
        slug: "electrical-engineering",
        ar: "هندسة كهربائية",
        he: "הנדסת חשמל",
        en: "Electrical engineering",
        levels: ["academic"],
      },
      {
        slug: "electrical-circuits",
        ar: "دوائر كهربائية",
        he: "מעגלים חשמליים",
        en: "Electrical circuits",
        levels: ["academic"],
      },
      {
        slug: "signals-systems",
        ar: "إشارات وأنظمة",
        he: "אותות ומערכות",
        en: "Signals and systems",
        levels: ["academic"],
      },
      {
        slug: "statics",
        ar: "سكونيات",
        he: "סטטיקה",
        en: "Statics",
        levels: ["academic"],
      },
      {
        slug: "dynamics",
        ar: "ديناميكا",
        he: "דינמיקה",
        en: "Dynamics",
        levels: ["academic"],
      },
      {
        slug: "strength-of-materials",
        ar: "مقاومة المواد",
        he: "חוזק חומרים",
        en: "Strength of materials",
        levels: ["academic"],
      },
      {
        slug: "thermodynamics",
        ar: "ثرموديناميكا",
        he: "תרמודינמיקה",
        en: "Thermodynamics",
        levels: ["academic"],
      },
      {
        slug: "civil-engineering",
        ar: "هندسة مدنية",
        he: "הנדסה אזרחית",
        en: "Civil engineering",
        levels: ["academic"],
      },
      {
        slug: "mechanical-engineering",
        ar: "هندسة ميكانيكية",
        he: "הנדסת מכונות",
        en: "Mechanical engineering",
        levels: ["academic"],
      },
      {
        slug: "industrial-engineering",
        ar: "هندسة صناعية وإدارة",
        he: "הנדסת תעשייה וניהול",
        en: "Industrial engineering and management",
        levels: ["academic"],
      },
    ],
  },

  {
    slug: "computing",
    ar: "حاسوب وبرمجة",
    he: "מחשבים ותכנות",
    en: "Computing and programming",
    subjects: [
      {
        slug: "python",
        ar: "بايثون",
        he: "פייתון",
        en: "Python",
        aliases: ["python"],
        levels: ["high", "academic", "enrichment"],
        featured: true,
      },
      {
        slug: "java",
        ar: "جافا",
        he: "ג'אווה",
        en: "Java",
        aliases: ["java"],
        levels: ["high", "academic"],
      },
      {
        slug: "c-programming",
        ar: "لغة C",
        he: "שפת C",
        en: "C",
        aliases: ["c"],
        levels: ["academic"],
      },
      {
        slug: "cpp",
        ar: "لغة ++C",
        he: "שפת ++C",
        en: "C++",
        aliases: ["cpp", "c++"],
        levels: ["academic"],
      },
      {
        slug: "javascript",
        ar: "جافاسكريبت",
        he: "ג'אווהסקריפט",
        en: "JavaScript",
        aliases: ["js", "javascript"],
        levels: ["academic", "enrichment"],
      },
      {
        slug: "sql",
        ar: "SQL",
        he: "SQL",
        en: "SQL",
        aliases: ["sql"],
        levels: ["academic", "professional"],
      },
      {
        slug: "data-structures",
        ar: "بنى معطيات",
        he: "מבני נתונים",
        en: "Data structures",
        levels: ["academic"],
      },
      {
        slug: "algorithms",
        ar: "خوارزميات",
        he: "אלגוריתמים",
        en: "Algorithms",
        levels: ["academic"],
      },
      {
        slug: "operating-systems",
        ar: "أنظمة تشغيل",
        he: "מערכות הפעלה",
        en: "Operating systems",
        levels: ["academic"],
      },
      {
        slug: "databases",
        ar: "قواعد بيانات",
        he: "בסיסי נתונים",
        en: "Databases",
        levels: ["academic"],
      },
      {
        slug: "web-development",
        ar: "تطوير مواقع",
        he: "בניית אתרים",
        en: "Web development",
        levels: ["enrichment", "professional"],
      },
    ],
  },

  {
    slug: "health-sciences",
    ar: "علوم صحية",
    he: "מדעי הבריאות",
    en: "Health sciences",
    subjects: [
      {
        slug: "anatomy",
        ar: "تشريح",
        he: "אנטומיה",
        en: "Anatomy",
        levels: ["academic"],
      },
      {
        slug: "physiology",
        ar: "فسيولوجيا",
        he: "פיזיולוגיה",
        en: "Physiology",
        levels: ["academic"],
      },
      {
        slug: "biochemistry",
        ar: "كيمياء حيوية",
        he: "ביוכימיה",
        en: "Biochemistry",
        levels: ["academic"],
      },
      {
        slug: "microbiology",
        ar: "أحياء دقيقة",
        he: "מיקרוביולוגיה",
        en: "Microbiology",
        levels: ["academic"],
      },
      {
        slug: "pharmacology",
        ar: "علم الأدوية",
        he: "פרמקולוגיה",
        en: "Pharmacology",
        levels: ["academic"],
      },
      {
        slug: "pathology",
        ar: "علم الأمراض",
        he: "פתולוגיה",
        en: "Pathology",
        levels: ["academic"],
      },
      {
        slug: "immunology",
        ar: "مناعة",
        he: "אימונולוגיה",
        en: "Immunology",
        levels: ["academic"],
      },
      {
        slug: "nursing",
        ar: "تمريض",
        he: "סיעוד",
        en: "Nursing",
        levels: ["academic"],
      },
      {
        slug: "research-methods",
        ar: "مناهج البحث",
        he: "שיטות מחקר",
        en: "Research methods",
        levels: ["academic"],
      },
    ],
  },

  {
    slug: "law",
    ar: "قانون",
    he: "משפטים",
    en: "Law",
    subjects: [
      {
        slug: "introduction-to-law",
        ar: "مدخل للقانون",
        he: "מבוא למשפט",
        en: "Introduction to law",
        levels: ["academic"],
      },
      {
        slug: "contract-law",
        ar: "قانون العقود",
        he: "דיני חוזים",
        en: "Contract law",
        levels: ["academic"],
      },
      {
        slug: "criminal-law",
        ar: "قانون العقوبات",
        he: "דיני עונשין",
        en: "Criminal law",
        levels: ["academic"],
      },
      {
        slug: "tort-law",
        ar: "قانون الأضرار",
        he: "דיני נזיקין",
        en: "Tort law",
        levels: ["academic"],
      },
      {
        slug: "constitutional-law",
        ar: "قانون دستوري",
        he: "משפט חוקתי",
        en: "Constitutional law",
        levels: ["academic"],
      },
      {
        slug: "bar-exam",
        ar: "امتحانات نقابة المحامين",
        he: "בחינות לשכת עורכי הדין",
        en: "Bar examinations",
        levels: ["professional"],
      },
    ],
  },

  {
    slug: "languages",
    ar: "لغات",
    he: "שפות",
    en: "Languages",
    subjects: [
      {
        slug: "spoken-hebrew",
        ar: "عبري محادثة",
        he: "עברית מדוברת",
        en: "Spoken Hebrew",
        levels: ["enrichment"],
        featured: true,
      },
      {
        slug: "spoken-english",
        ar: "إنجليزي محادثة",
        he: "אנגלית מדוברת",
        en: "Spoken English",
        levels: ["enrichment"],
      },
      {
        slug: "arabic-for-hebrew-speakers",
        ar: "عربية لغير الناطقين بها",
        he: "ערבית לדוברי עברית",
        en: "Arabic for Hebrew speakers",
        levels: ["enrichment"],
      },
      {
        slug: "turkish",
        ar: "تركية",
        he: "טורקית",
        en: "Turkish",
        levels: ["enrichment"],
      },
      {
        slug: "german",
        ar: "ألمانية",
        he: "גרמנית",
        en: "German",
        levels: ["enrichment"],
      },
      {
        slug: "french",
        ar: "فرنسية",
        he: "צרפתית",
        en: "French",
        levels: ["enrichment"],
      },
      {
        slug: "spanish",
        ar: "إسبانية",
        he: "ספרדית",
        en: "Spanish",
        levels: ["enrichment"],
      },
      {
        slug: "russian",
        ar: "روسية",
        he: "רוסית",
        en: "Russian",
        levels: ["enrichment"],
      },
    ],
  },

  {
    slug: "special-education",
    ar: "تربية خاصة وتعليم علاجي",
    he: "חינוך מיוחד והוראה מתקנת",
    en: "Special education",
    subjects: [
      {
        slug: "corrective-reading",
        ar: "تعليم علاجي - قراءة",
        he: "הוראה מתקנת - קריאה",
        en: "Corrective teaching — reading",
        levels: ["elementary", "middle"],
      },
      {
        slug: "corrective-writing",
        ar: "تعليم علاجي - كتابة",
        he: "הוראה מתקנת - כתיבה",
        en: "Corrective teaching — writing",
        levels: ["elementary", "middle"],
      },
      {
        slug: "corrective-mathematics",
        ar: "تعليم علاجي - حساب",
        he: "הוראה מתקנת - חשבון",
        en: "Corrective teaching — mathematics",
        levels: ["elementary", "middle"],
      },
      {
        slug: "learning-difficulties",
        ar: "صعوبات تعلّم",
        he: "לקויות למידה",
        en: "Learning difficulties",
        levels: ["elementary", "middle", "high"],
      },
      {
        slug: "adhd-support",
        ar: "تشتت وفرط حركة",
        he: "הפרעות קשב וריכוז",
        en: "ADHD support",
        levels: ["elementary", "middle", "high"],
      },
      {
        slug: "grade-1-preparation",
        ar: "تحضير للصف الأول",
        he: "הכנה לכיתה א'",
        en: "Grade 1 preparation",
        levels: ["elementary"],
      },
    ],
  },

  {
    slug: "music",
    ar: "موسيقى",
    he: "מוזיקה",
    en: "Music",
    subjects: [
      {
        slug: "oud",
        ar: "عود",
        he: "עוד",
        en: "Oud",
        aliases: ["oud", "عود"],
        levels: ["enrichment"],
      },
      {
        slug: "qanun",
        ar: "قانون",
        he: "קאנון",
        en: "Qanun",
        levels: ["enrichment"],
      },
      {
        slug: "darbuka",
        ar: "دربكة",
        he: "דרבוקה",
        en: "Darbuka",
        levels: ["enrichment"],
      },
      {
        slug: "ney",
        ar: "ناي",
        he: "נאי",
        en: "Ney",
        levels: ["enrichment"],
      },
      {
        slug: "piano",
        ar: "بيانو",
        he: "פסנתר",
        en: "Piano",
        levels: ["enrichment"],
      },
      {
        slug: "guitar",
        ar: "جيتار",
        he: "גיטרה",
        en: "Guitar",
        levels: ["enrichment"],
      },
      {
        slug: "violin",
        ar: "كمان",
        he: "כינור",
        en: "Violin",
        levels: ["enrichment"],
      },
      {
        slug: "singing",
        ar: "غناء وتطوير صوت",
        he: "פיתוח קול",
        en: "Singing and voice",
        levels: ["enrichment"],
      },
      {
        slug: "music-theory",
        ar: "نظريات الموسيقى",
        he: "תיאוריה מוזיקלית",
        en: "Music theory",
        levels: ["enrichment"],
      },
    ],
  },

  {
    slug: "religious-studies",
    ar: "علوم دينية",
    he: "לימודי דת",
    en: "Religious studies",
    subjects: [
      {
        slug: "quran-tajweed",
        ar: "تجويد وتلاوة",
        he: "טג'וויד וקריאת קוראן",
        en: "Quran recitation and tajweed",
        aliases: ["tajweed", "قرآن"],
        levels: ["enrichment"],
      },
      {
        slug: "quran-memorisation",
        ar: "تحفيظ قرآن",
        he: "שינון קוראן",
        en: "Quran memorisation",
        levels: ["enrichment"],
      },
      {
        slug: "islamic-jurisprudence",
        ar: "فقه إسلامي",
        he: "פיקה אסלאמי",
        en: "Islamic jurisprudence",
        levels: ["enrichment", "academic"],
      },
      {
        slug: "bible-studies",
        ar: "دراسات الكتاب المقدس",
        he: "לימודי הברית",
        en: "Bible studies",
        levels: ["enrichment"],
      },
    ],
  },

  {
    slug: "skills",
    ar: "مهارات وإثراء",
    he: "מיומנויות והעשרה",
    en: "Skills and enrichment",
    subjects: [
      {
        slug: "study-skills",
        ar: "مهارات تعلّم",
        he: "מיומנויות למידה",
        en: "Study skills",
        levels: ["enrichment"],
      },
      {
        slug: "exam-anxiety",
        ar: "التعامل مع قلق الامتحانات",
        he: "התמודדות עם חרדת בחינות",
        en: "Exam anxiety",
        levels: ["enrichment"],
      },
      {
        slug: "programming-for-kids",
        ar: "برمجة للأطفال",
        he: "תכנות לילדים",
        en: "Programming for kids",
        levels: ["enrichment"],
      },
      {
        slug: "drawing",
        ar: "رسم",
        he: "ציור",
        en: "Drawing",
        levels: ["enrichment"],
      },
      {
        slug: "chess",
        ar: "شطرنج",
        he: "שחמט",
        en: "Chess",
        levels: ["enrichment"],
      },
    ],
  },
];

/** Flat list — every leaf subject, category order preserved. */
export const allSubjects = categories.flatMap((category) =>
  category.subjects.map((subject) => ({
    ...subject,
    categorySlug: category.slug,
    isExam: category.isExam ?? false,
  })),
);

export const featuredSubjects = allSubjects.filter(
  (subject) => subject.featured && !subject.isExam,
);

export const featuredExams = allSubjects.filter(
  (subject) => subject.featured && subject.isExam,
);

export function findSubject(slug: string) {
  return allSubjects.find((subject) => subject.slug === slug);
}
